### ISSUE TITLE
C&C and SSH Bruteforce?

### ISSUE THREAD

**Issue by a11y-spec** [Senc3951/Ransomware#3]
Hello i am pretty much inspired from your project as i see in the TODO list you can use SSH Bruteforce for network spreading or Powershell based attacks as for C&C you can use a php site to send the keys? 
like- url = 'http://www.site.com/alert.php'.
I would also like to help in this if you don't mind.

**Comment by Senc3951** [comment]
I don't mind, I thought about CnC but you need a website for this, which I don't have...

**Comment by a11y-spec** [comment]
> I don't mind, I thought about CnC but you need a website for this, which I don't have...

Whoa I didn't expected much fast reply as for the website i will make it.

**Comment by Senc3951** [comment]
Sure!

**Comment by a11y-spec** [comment]
also i was wondering if you have any social accounts were i could contact you for any help sorry for asking such a useless question.

**Comment by Senc3951** [comment]
I can give you but perhaps you have discord? If no I'll give you my social account

**Comment by a11y-spec** [comment]
Discord will work Thanks in advance!
