### ISSUE TITLE
New repo/project

### ISSUE THREAD

**Issue by AspectKraken** [Senc3951/Ransomware#6]
Can u create a completely silent downloader and runner
 that runs with 
persistence for registry
online download ( so the python file isn't in the file it downloads it over the internet )
Uac bypass then auto upgrade to System
runs fully silently and secretly with Rootkit so its undetectable from process hacker rather than it not running with it open. 
add a timer

**Comment by Senc3951** [comment]
Everything you wrote is possible, I don't want to take the project to this phase because it's not necessary...
But I uploaded first_payload.py which is the silent downloaded and runner, all you need is a link to the .exe file
For the UAC bypass to get system, you can use psexec

**Comment by AspectKraken** [comment]
psexec what is that?

**Comment by AspectKraken** [comment]
and can u put instructions of it in Readme ?

**Comment by AspectKraken** [comment]
and add a python obfuscator or the compiled exe obfuscator in read me?

**Comment by Senc3951** [comment]
Yes, I will not make obfuscator because you can make your own, just rename everything to stuff like this:jtkeo85oJ, and replace the strings.

You can check what psexec is
